name: Deploy Fabular Content to Pages
# ... (rest of the file remains the same)
      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # *** Reverting to deploy the whole Fabular_Website folder ***
          path: 'Fabular_Website'
          
      - name: Deploy to GitHub Pages
# ... (rest of the file remains the same)
